- id: '1606323379512'
  alias: Notification when wife leaves work
  description: ''
  trigger:
  - platform: zone
    entity_id: person.trish
    zone: zone.trish_s_work
    event: leave
  condition: []
  action:
  - service: notify.mobile_app_mikes_iphone
    data:
      message: Wife is on her way home from work.
      title: Wife
  mode: single
- id: '1606323478829'
  alias: Notification when wife arrives home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.trish
    zone: zone.home
    event: enter
  condition:
  - condition: state
    entity_id: person.mike
    state: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - service: notify.mobile_app_mikes_iphone
    data:
      message: Wife is home.
      title: Wife
  mode: single
- id: '1610953656599'
  alias: Shut off all lights
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Goodnight
  condition: []
  action:
  - domain: light
    entity_id: light.bedroom_lamp_left
    device_id: 4a50679438ce4fcbba908d6ed5acd59d
    type: turn_off
  - domain: light
    entity_id: light.bedroom_lamp_right
    device_id: 2adff8e7c96a4a7d9867e6fedd4d01b8
    type: turn_off
  - type: turn_off
    device_id: 97a81863e6dbd575534d5522ccd7034e
    entity_id: light.living_room_lamp
    domain: light
  - type: turn_off
    device_id: bee413e15980480a9d50889519b55aff
    entity_id: light.office_lamp
    domain: light
  - type: turn_off
    device_id: bec2d42db3c544709390bdb2870e0f98
    entity_id: light.kitchen_lights
    domain: light
  - type: turn_off
    device_id: 794ca41f8f5941ac9cccbfd4cf66ecbb
    entity_id: light.office_bookshelf_bloom
    domain: light
  - type: turn_off
    device_id: 5df6e8e94f57437498f57fedd091b127
    entity_id: switch.smart_outlet_01_switch
    domain: switch
  - type: turn_off
    device_id: 739e6b15044345985c552c3192f108bd
    entity_id: switch.smart_outlet_02_switch
    domain: switch
  mode: single
- id: '1626362442938'
  alias: Light Button - Toggle Living Room Lamp
  description: ''
  trigger:
  - device_id: d2f42206556c48aeaa2004cfbf737c24
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: 97a81863e6dbd575534d5522ccd7034e
    entity_id: light.living_room_lamp
    domain: light
  mode: single
- id: '1649734825274'
  alias: Dehumidifier - Send notification when full
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.dehumidifier_bucket
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      message: The dehumidifier is full.
      data:
        type: announce
        method: all
      target:
      - media_player.living_room_show
      - media_player.kitchen_dot
      - media_player.master_bedroom_echo_spot
    enabled: false
  - service: notify.notify
    data:
      message: The dehumidifier is full.
      title: Dehumidifier
  mode: single
- id: '1662251793455'
  alias: Away - Performs action when everyone leaves home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.household
    to: not_home
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: script.away_camera_start_recording
    data: {}
  mode: single
- id: '1662251855162'
  alias: Home - Performs action when someone comes home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.household
    to: home
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: script.home_camera_stop_recording
    data: {}
  mode: single
- id: '1667955153429'
  alias: Sprinklers - Pause If Back Door Opens
  description: Pause the sprinklers for 15 minutes if they are on when the back door
    opens
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.back_door_sensor
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.backyard
      state: 'on'
    - condition: state
      entity_id: switch.backyard_patio
      state: 'on'
  action:
  - service: rachio.pause_watering
    data:
      duration: 15
  mode: single
- id: '1669497816229'
  alias: Christmas Lights - Turn on at night
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:15:00
  condition: []
  action:
  - service: homeassistant.turn_on
    data: {}
    target:
      entity_id:
      - switch.exterior_outdoor_smart_plug
  mode: single
- id: '1669497868697'
  alias: Christmas Lights - Turn off at 12am
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id: switch.exterior_outdoor_smart_plug
  mode: single
