- id: '1606323379512'
  alias: Notification when wife leaves work
  description: ''
  trigger:
  - platform: zone
    entity_id: person.trish
    zone: zone.trish_s_work
    event: leave
  condition: []
  action:
  - service: notify.mobile_app_mike_s_iphone
    data:
      message: Wife is on her way home from work.
  mode: single
- id: '1606323478829'
  alias: Notification when wife arrives home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.trish
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_mike_s_iphone
    data:
      message: Wife is home.
  mode: single
- id: '1610953656599'
  alias: Shut off all lights
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Goodnight
  condition: []
  action:
  - domain: light
    entity_id: light.bedroom_lamp_left
    device_id: 4a50679438ce4fcbba908d6ed5acd59d
    type: turn_off
  - domain: light
    entity_id: light.bedroom_lamp_right
    device_id: 2adff8e7c96a4a7d9867e6fedd4d01b8
    type: turn_off
  - type: turn_off
    device_id: e6b133367549409daa60556885d14b49
    entity_id: light.living_room_lamp
    domain: light
  - type: turn_off
    device_id: bee413e15980480a9d50889519b55aff
    entity_id: light.office_lamp
    domain: light
  mode: single
- id: '1626362442938'
  alias: Light Button - Toggle Living Room Lamp
  description: ''
  trigger:
  - device_id: d2f42206556c48aeaa2004cfbf737c24
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: 97a81863e6dbd575534d5522ccd7034e
    entity_id: light.living_room_lamp
    domain: light
  mode: single
