- id: '1606323379512'
  alias: Notification when wife leaves work
  description: ''
  trigger:
  - platform: zone
    entity_id: person.trish
    zone: zone.trish_s_work
    event: leave
  condition: []
  action:
  - service: notify.mobile_app_mikes_iphone
    data:
      message: Wife is on her way home from work.
      title: Wife
  mode: single
- id: '1606323478829'
  alias: Notification when wife arrives home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.trish
    zone: zone.home
    event: enter
  condition:
  - condition: state
    entity_id: person.mike
    state: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - service: notify.mobile_app_mikes_iphone
    data:
      message: Wife is home.
      title: Wife
  mode: single
- id: '1610953656599'
  alias: Shut off all lights
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Goodnight
  condition: []
  action:
  - domain: light
    entity_id: light.bedroom_lamp_left
    device_id: 4a50679438ce4fcbba908d6ed5acd59d
    type: turn_off
  - domain: light
    entity_id: light.bedroom_lamp_right
    device_id: 2adff8e7c96a4a7d9867e6fedd4d01b8
    type: turn_off
  - type: turn_off
    device_id: 11219fe9c3294acd2502a8abe0cac72c
    entity_id: ec12ade7c240de5ac1e3bc43d41577dc
    domain: light
  - type: turn_off
    device_id: a79b842b4137b12d144a6fd377abd704
    entity_id: 1848f38c479266833fe079e6077703dd
    domain: light
  - type: turn_off
    device_id: bec2d42db3c544709390bdb2870e0f98
    entity_id: light.kitchen_lights
    domain: light
  - type: turn_off
    device_id: 5df6e8e94f57437498f57fedd091b127
    entity_id: switch.smart_outlet_01_switch
    domain: switch
  - type: turn_off
    device_id: 739e6b15044345985c552c3192f108bd
    entity_id: switch.smart_outlet_02_switch
    domain: switch
  mode: single
- id: '1626362442938'
  alias: Light Button - Toggle Living Room Lamp
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 6793e66057e2677f386d017157af701e
    type: action
    subtype: single
    discovery_id: 0x286d9700010df23d action_single
  condition: []
  action:
  - type: toggle
    device_id: 11219fe9c3294acd2502a8abe0cac72c
    entity_id: ec12ade7c240de5ac1e3bc43d41577dc
    domain: light
  mode: single
- id: '1649734825274'
  alias: Dehumidifier - Send notification when full
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.finished_basement_tank_full
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      message: The dehumidifier is full.
      data:
        type: announce
        method: all
      target:
      - media_player.living_room_show
      - media_player.kitchen_dot
      - media_player.master_bedroom_echo_spot
    enabled: false
  - service: notify.notify
    data:
      message: The dehumidifier is full.
      title: Dehumidifier
  mode: single
- id: '1662251793455'
  alias: Away - Performs action when everyone leaves home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.household
    to: not_home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: script.away_camera_start_recording
    data: {}
  - device_id: 049a897f1005af31c9a8eb0725fda744
    domain: alarm_control_panel
    entity_id: c9d9b464bdbd8c1fd71f06c5534fbeaf
    type: arm_away
  mode: single
- id: '1662251855162'
  alias: Home - Performs action when someone comes home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.household
    to: home
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: script.home_camera_stop_recording
    data: {}
  - device_id: 049a897f1005af31c9a8eb0725fda744
    domain: alarm_control_panel
    entity_id: c9d9b464bdbd8c1fd71f06c5534fbeaf
    type: disarm
  mode: single
- id: '1667955153429'
  alias: Sprinklers - Pause If Back Door Opens
  description: Pause the sprinklers for 15 minutes if they are on when the back door
    opens
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.back_door_sensor
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.backyard
      state: 'on'
    - condition: state
      entity_id: switch.backyard_patio
      state: 'on'
  action:
  - service: rachio.pause_watering
    data:
      duration: 15
  mode: single
- id: '1669497816229'
  alias: Christmas Lights - Turn on at night
  description: ''
  triggers:
  - event: sunset
    offset: 00:15:00
    trigger: sun
  conditions:
  - condition: state
    entity_id: input_select.holiday
    state: christmas
  actions:
  - data: {}
    target:
      entity_id: switch.exterior_christmas_lights
    action: homeassistant.turn_on
  mode: single
- id: '1669497868697'
  alias: Christmas Lights - Turn off at 12am
  description: ''
  triggers:
  - at: 00:00:00
    trigger: time
  conditions:
  - condition: state
    entity_id: input_select.holiday
    state: christmas
  actions:
  - data: {}
    target:
      entity_id: switch.exterior_christmas_lights
    action: homeassistant.turn_off
  mode: single
- id: '1689447603826'
  alias: Dehumidifier - Turn On
  description: Turns on dehumidifier when it reaches target temperature.
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.basement_wave_plus_humidity'') | float >=
      (states(''input_number.basement_humidity_target'') | float + 5.0) }}'
  condition: []
  action:
  - service: humidifier.turn_on
    data: {}
    target:
      entity_id: humidifier.finished_basement
  mode: single
- id: '1689447830700'
  alias: Dehumidifier - Turn Off
  description: Turns off dehumidifier when it gets to target humidity.
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.basement_wave_plus_humidity'') | float <=
      states(''input_number.basement_humidity_target'') | float }}'
  condition: []
  action:
  - service: humidifier.turn_off
    data: {}
    target:
      entity_id: humidifier.finished_basement
  mode: single
- id: '1697431247538'
  alias: Car Charger - Send Notification when done charging
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.tesla_wall_connector_contactor_closed
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
    state: 'on'
  action:
  - service: notify.notify
    data:
      message: Car finished charging in {{ now() - states('input_datetime.car_charger_start_time')
        | as_datetime | as_local }}
      title: Car Charging
  mode: single
- id: '1697431620883'
  alias: Car Charger - Log when charging starts
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.tesla_wall_connector_contactor_closed
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
    from:
  condition: []
  action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.car_charger_start_time
    data:
      datetime: '{{ now() }}'
  mode: single
- id: '1701058348236'
  alias: Button - Trigger Goodnight Scene
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 4bef945ee6b1d8fe513a0be60895894f
    type: action
    subtype: single
    discovery_id: 0x286d9700010d0502 action_single
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.bedtime
    metadata: {}
  mode: single
- id: '1705850483652'
  alias: Notify when server power turned off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 50cae035aaae343107f99e909fe04d0c
    entity_id: 66b6198b408cfa590a68f7b76a1dfd46
    domain: switch
  - platform: device
    type: turned_off
    device_id: 8cc20e25511369c52238e53a8679cc41
    entity_id: de9b94cf363962cf761ce474a313bec2
    domain: switch
  condition: []
  action:
  - service: notify.mobile_app_mikes_iphone
    data:
      message: Server or Office PC turned off
  mode: single
- id: '1716868591290'
  alias: Dehumidifier - Failsafe
  description: Turns off the dehumidifier if it has been running for an hour and is
    below the target humidity.
  trigger:
  - platform: device
    type: turned_on
    device_id: 5699bfac3d624082eb1296bb5abea4ae
    entity_id: b4f5a80eff42e1e6836bd0fa3f76c9a1
    domain: humidifier
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition:
  - condition: template
    value_template: '{{ states(''sensor.basement_wave_plus_humidity'') | float <=
      states(''input_number.basement_humidity_target'') | float }}'
  action:
  - service: humidifier.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 5699bfac3d624082eb1296bb5abea4ae
  mode: single
- id: '1722979593224'
  alias: Water Leak - Notify
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.boiler_leak_sensor_water_leak_detected
    - binary_sensor.basement_window_leak_sensor_water_leak_detected
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: '{{ trigger.to_state.attributes.friendly_name }}'
      title: Water leak detected!
  mode: single
- id: '1733375681429'
  alias: Unlock Front Door Doorbell Fingerprint Scan
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: -C0WkpGeL02Mj6DMGpUhBib-H
  conditions: []
  actions:
  - device_id: 5a50bf00a9315164b2ecd994eb4ae5a3
    domain: lock
    entity_id: 2f52706b20d9b688d266c929ff0abbed
    type: unlock
  mode: single
- id: '1735199383943'
  alias: Ecobee - Switch to aux heat
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.spare_bedroom_temphumi_sensor_air_temperature
    - sensor.upstairs_bathroom_temphumi_sensor_air_temperature
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: 62
  conditions:
  - condition: device
    device_id: d8051410a12924ca3c9525cbf65a3931
    domain: climate
    entity_id: c939ced0e85b2a06f0361dd6aa982add
    type: is_hvac_mode
    hvac_mode: 'off'
  - condition: not
    conditions:
    - condition: device
      device_id: 050d5c841a24c29630ba3b324e85d264
      domain: climate
      entity_id: 4a99efe78e3766b9e0cbe5786988d84c
      type: is_hvac_mode
      hvac_mode: cool
  - condition: state
    entity_id: input_boolean.hvac_dual_fuel_auto_switch
    state: 'on'
  actions:
  - action: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: heat
    target:
      device_id: d8051410a12924ca3c9525cbf65a3931
  - device_id: 050d5c841a24c29630ba3b324e85d264
    domain: climate
    entity_id: 4a99efe78e3766b9e0cbe5786988d84c
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1735199552338'
  alias: Ecobee - Switch to primary heat
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.upstairs_bathroom_temphumi_sensor_air_temperature
    - sensor.spare_bedroom_temphumi_sensor_air_temperature
    for:
      hours: 0
      minutes: 0
      seconds: 0
    above: 64
  conditions:
  - condition: and
    conditions:
    - condition: device
      device_id: d8051410a12924ca3c9525cbf65a3931
      domain: climate
      entity_id: c939ced0e85b2a06f0361dd6aa982add
      type: is_hvac_mode
      hvac_mode: heat
    - condition: state
      entity_id: input_boolean.hvac_dual_fuel_auto_switch
      state: 'on'
  actions:
  - action: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: heat
    target:
      device_id: 050d5c841a24c29630ba3b324e85d264
  - action: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: 'off'
    target:
      device_id: d8051410a12924ca3c9525cbf65a3931
  mode: single
- id: '1735283343009'
  alias: Espresso Machine - Notify when on too long
  description: ''
  triggers:
  - type: turned_on
    device_id: 6b6441025166bcafa9493d26e6b7b885
    entity_id: 47b207e21c8a6ecbf5a6a0e8775cc22e
    domain: switch
    trigger: device
    for:
      hours: 2
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - data:
      message: Espresso Machine has been on for 2 hours.
      title: Espresso Machine
    action: notify.mobile_app_mikes_iphone
  mode: single
- id: '1739683264585'
  alias: Button - Turn on Office Lamp
  description: ''
  triggers:
  - domain: mqtt
    device_id: 0b384da99922d2aac96794c88fae560f
    type: action
    subtype: config_single
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      device_id: 33aa22486fda0bfed0fd696b08928fe4
  mode: single
- id: '1739861696187'
  alias: Office Air Purifier - Turn On
  description: ''
  triggers:
  - type: occupied
    device_id: 78af804be124fbb2800a9a499d743aac
    entity_id: 34844f9a791400e5ac36c01ab642f0ac
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 10
      seconds: 0
  conditions:
  - condition: device
    device_id: ff4454949c98c1a706c7192cefa0d410
    domain: fan
    entity_id: ef2f5a6f935b77c549b64dc7b3403223
    type: is_off
  actions:
  - type: turn_on
    device_id: ff4454949c98c1a706c7192cefa0d410
    entity_id: ef2f5a6f935b77c549b64dc7b3403223
    domain: fan
  - action: fan.set_percentage
    metadata: {}
    data:
      percentage: 25
    target:
      device_id: ff4454949c98c1a706c7192cefa0d410
  mode: single
- id: '1739861948576'
  alias: Office Air Purifier - Turn Off
  description: ''
  triggers:
  - type: not_occupied
    device_id: 78af804be124fbb2800a9a499d743aac
    entity_id: 34844f9a791400e5ac36c01ab642f0ac
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 30
      seconds: 0
  conditions:
  - condition: device
    device_id: ff4454949c98c1a706c7192cefa0d410
    domain: fan
    entity_id: ef2f5a6f935b77c549b64dc7b3403223
    type: is_on
  - condition: or
    conditions:
    - condition: time
      after: '18:00:00'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      before: 06:00:00
    - condition: time
      weekday:
      - sat
      - sun
  actions:
  - type: turn_off
    device_id: ff4454949c98c1a706c7192cefa0d410
    entity_id: ef2f5a6f935b77c549b64dc7b3403223
    domain: fan
  mode: single
- id: '1743533542473'
  alias: Turn on Pantry Light when Door Opens
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.pantry_door_window_door_is_open
    from:
    to: 'on'
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      area_id: pantry
  mode: single
- id: '1743533790033'
  alias: Turn off Pantry Light when door closes
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.pantry_door_window_door_is_open
    from: 'on'
    to: 'off'
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      area_id: pantry
  mode: single
