title: Home

resources: !include_dir_list lovelace/resources
custom_header: !include lovelace/cards/custom_header.yaml
background: center / cover no-repeat url("/local/image/background.jpeg") fixed

views:
  - !include /config/lovelace/views/home.yaml
  - !include /config/lovelace/views/livingroom.yaml
  - !include /config/lovelace/views/bedroom.yaml
  - !include /config/lovelace/views/office.yaml
  - !include /config/lovelace/views/outside.yaml
  - !include /config/lovelace/views/status.yaml
#  - !include /config/lovelace/views/log.yaml
  - !include /config/lovelace/views/home_panel.yaml
  - !include /config/lovelace/views/climate.yaml
  - !include /config/lovelace/views/livingroomrokuremote.yaml
