title: Home

resources: !include_dir_list lovelace/resources
cch: !include lovelace/cards/compact_custom_header.yaml

views:
        - !include /config/lovelace/views/home.yaml
        - !include /config/lovelace/views/livingroom.yaml
        - !include /config/lovelace/views/bedroom.yaml
        - !include /config/lovelace/views/office.yaml
        - !include /config/lovelace/views/outside.yaml
        - !include /config/lovelace/views/status.yaml
