- '2024-12-25' # Christmas Day
- '2025-01-01' # New Years Day
- '2025-01-20' # Martin Luther King Jr. Day
- '2025-02-17' # Presidents Day
- '2025-05-26' # Memorial Day
- '2025-06-19' # Juneteenth
- '2025-07-04' # Independence Day
- '2025-09-01' # Labor Day
- '2025-10-13' # Columbus Day
- '2025-11-11' # Veterans Day
- '2025-11-27' # Thanksgiving
- '2025-11-28' # Day after Thanksgiving
- '2025-12-25' # Christmas Day