# Town of Hempstead 2026 recycling holidays - Thursday route (no make-up days)
# https://hempsteadny.gov/227/Recycling-Holiday-Collection-Schedule
- '2026-01-01' # New Years Day
- '2026-11-26' # Thanksgiving
