---
type: vertical-stack
view_layout:
  grid-area: security
cards:
  - type: custom:bubble-card
    card_type: separator
    name: Security
    icon: mdi:security
  - type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: 1fr 1fr
      grid-template-rows: 1fr 1fr
      grid-template-areas: |
        "frontlock alarmo"
        "basementlock ."
    cards:
      - type: tile
        name: Front
        entity: lock.front_door_lock
        features:
          - type: "lock-commands"
        view_layout:
          grid-area: frontlock

      - type: tile
        name: Alarm
        entity: alarm_control_panel.alarmo
        features:
          - type: "alarm-modes"
            modes:
              - armed_away
              - disarmed
        view_layout:
          grid-area: alarmo

      - type: tile
        name: Basement
        entity: lock.basement_door_lock
        features:
          - type: "lock-commands"
        view_layout:
          grid-area: basementlock