---
type: horizontal-stack
view_layout:
  grid-area: security
cards:
  - type: tile
    name: Front Door
    entity: lock.front_door_lock
    show_name: false
    features:
    - type: "lock-commands"
  - type: tile
    show_name: false
    entity: alarm_control_panel.alarmo
    name: Alarm
    features:
      - type: "alarm-modes"
        modes:
          - armed_away
          - disarmed