---
- alias: Away - Performs actions when everyone leaves home
  trigger:
    platform: state
    entity_id: group.household
    to: "not_home"
    for:
      "00:10:00"
  action:
    service: script.away

- alias: Home - Performs actions when someone arrives home
  trigger:
    platform: state
    entity_id: group.household
    to: "home"
  action:
    service: script.home
