---
# ---------------------------------
# Automations for Christmas lights.
# ---------------------------------

# Turn on christmas lights 15 minutes after sunset.
- alias: 'Christmas Lights - Turn on at night'
  trigger:
    - platform: sun
      event: sunset
      offset: '00:15:00'
  action:
    - service: homeassistant.turn_on
      entity_id: group.outdoor_christmas_lights

# Turn off the christmas lights 8 hours after sunset.
- alias: 'Christmas Lights - Turn off 8 hours after sunset'
  trigger:
    - platform: sun
      event: sunset
      offset: '08:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: group.outdoor_christmas_lights
