---
- alias: Leak Sensor - Notify when leak detected
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.basement_leak_sensor
        - binary_sensor.washer_leak_sensor
        - binary_sensor.downstairs_bathroom_sink_leak_sensor
        - binary_sensor.kitchen_sink_leak_sensor
      from: "off"
      to: "on"
  action:
    - service: notify.ios_mikes_iphone
      data_template:
        message: '{{ trigger.to_state.attributes.friendly_name }} detected a water leak.'
        title: 'Water Leak Detected'