---
# Toggle living room lights when button is clicked.
- alias: Living Room Button - Toggle living room lights
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: 28:6d:97:00:01:0d:f2:3d
      command: button_single
  action:
    service: homeassistant.toggle
    entity_id: light.living_room_lamp