alias: "Mail Notification - Mail Delieveries"
initial_state: 'on'
trigger:
#Trigger if mail or packages get updated
  - platform: state
    entity_id: sensor.mail_usps_mail
  - platform: state
    entity_id: sensor.mail_usps_delivering
#send only if mail or packages are more than 0
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ states('sensor.mail_usps_mail') | int > 0 }}"
      - condition: template
        value_template: "{{ states('sensor.mail_usps_delivering') | int > 0 }}"
action:
  - service: notify.ios_mikes_phone
    data_template:
      title: "*Today's Mail and Packages*"
      message: "{{ states('sensor.mail_deliveries_message')}}"
  - service: notify.ios_mikes_phone
    data:
      message: "Here is the mail"
      data:
        document:
          file: "/config/www/image/mail_and_packages/mail_today.gif"