---
# Push notification when neato exception occurs
- alias: Neato - Send exception notification
  trigger:
    - platform: state
      entity_id: sensor.vacuum_state
      to: "Alfred: Please empty dust bin"
  action:
    - service: notify.mobile_app_mikes_iphone
      data_template:
        message: "{{ states('sensor.vacuum_state') }}"
    - service: persistent_notification.create
      data_template:
        title: "Neato BotVac Alert"
        notification_id: neato-botvac-alert
        message: >
          {{ states('sensor.vacuum_state') }}
