---
# Sets the home assistant theme on restart.
- alias: Set Theme
  trigger:
    - platform: homeassistant
      event: start
  condition: []
  action:
    - service: frontend.set_theme
      data:
        name: "ios-dark-mode"
        mode: "dark"