---
alias: 'Turn off the front porch light when motion ends'
trigger:
        platform: state
        entity_id: binary_sensor.ring_front_door_motion
        from: 'on'
        to: 'off'
        for:
                minutes: 5
action:
        service: light.turn_off
        entity_id: light.front_porch_light
