alias: 'Turn on front porch light after motion detected.'
trigger:
        platform: state
        entity_id: binary_sensor.ring_front_door_motion
        from: 'off'
        to: 'on'
condition:
        - condition: and
          conditions:
                  - condition: state
                    entity_id: sun.sun
                    state: below_horizon
                  - condition: time
                    after: '00:00:00'
action:
        service: light.turn_on
        entity_id: light.front_porch_light
