alias: 'Turn on front porch light at night'
trigger:
        - platform: sun
          event: sunset
          offset: '00:15:00'
condition:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
action:
        service: light.turn_on
        entity_id: light.front_porch_light
