---
alias: 'Turn Back Patio Light On When Back Door Opens'
trigger:
        - platform: state
          entity_id: binary_sensor.back_door_sensor
          from: 'off'
          to: 'on'
condition:
        condition: state
        entity_id: sun.sun
        state: below_horizon
action:
        - service: light.turn_on
          entity_id: light.back_patio_light
